### ISSUE TITLE
Bump version of enunciate

### ISSUE THREAD

**Issue by Mart-Bogdan** [stoicflame/enunciate-gradle#22]
there are issue in enunciate https://github.com/stoicflame/enunciate/issues/862 
Works for me on   id "com.webcohesion.enunciate" version "2.10.1"  but not on 2.11.1

Please bump plugin version or add config to allow switching enunciate version used by plugin

**Comment by jskov-jyskebank-dk** [comment]
@stoicflame forgot to bump the reference in the build.gradle file, before releasing the new version of this project.
Maybe do so, and release 2.11.1sr1 ?

**Comment by stoicflame** [comment]
I'm pretty sure I bumped the version before releasing. You're saying that the gradle plugin 2.11.1 doesn't depend on enunciate 2.11.1?

**Comment by jskov-jyskebank-dk** [comment]
My bad, @stoicflame . I did not see that the bugfix was from May *last year*. I thought you had cut a new bugfix release recently, and that did not match the commit dates on this project.

Anyway, @Mart-Bogdan, the referenced bug is a Maven problem. So that is clearly not what you are seeing.
If something similar, are you using java9? No? Java 11, maybe? If so, did you see the workaround in https://github.com/stoicflame/enunciate-gradle/issues/20 ?
