### ISSUE TITLE
Enunciate output is not regenerated when inputs change

### ISSUE THREAD

**Issue by jskov-jyskebank-dk** [stoicflame/enunciate-gradle#5]
At least when enunciate.xml (or build file) changes, output is not regenerated.

May be the cause of stoicflame/enunciate#245

Work around the problem by removing the build/enunciate folder, then run the enunciate task.

**Comment by stoicflame** [comment]
For what it's worth, at enunciate/05f0a5f I added code that will take into account the config file when calculating staleness.

**Comment by jskov-jyskebank-dk** [comment]
The staleness change did not have an effect.

But I am looking at <docs> only. I see this output:

Skipping documentation source generation as everything appears up-to-date...

So I think it is actually a problem in enunciate - in the docs plugin? @stoicflame ?

As a workaround, we can put this in the Gradle build file:

```
enunciate.doFirst { project.delete("build/enunciate") }
```

**Comment by stoicflame** [comment]
I can't prove that it's a not bug in the docs module, but the logic is pretty simple: compare the newest source file timestamp (including the config file) and if it's older than the newest file in the generated documentation directory, then the generated documentation is deemed "up to date" and the generation process is skipped.

If you run gradle with debug logging (`-d` switch), then it should print out a statement like "%s is up-to-date because its oldest file, %s, is younger than the youngest source file.", which should give more details.

**Comment by jskov-jyskebank-dk** [comment]
This is your output, @stoicflame :

```
C:\udvikler\ws\mars-test.git\jb.jbit.im.tools.buildserver\jb.jbit.im.tools.buildserver.rest.java\build\enunciate\docs is up-to-date because its oldest file, C:\udvikler\ws\mars-test.git\jb.jbit.im.tools.buildserver\jb.jbit.im.tools.buildserver.rest.java\build\enunciate\docs\css\style.css, is younger than the youngest source file.
```

This is after I changed the enunciate.xml file.

If I change one of the source files, it does trigger a new docs export.

So it looks like you need to also consider enunciate.xml in your up-to-date check for docs.

**Comment by stoicflame** [comment]
Confirmed.

Weird. I thought I fixed that at [e096e7](https://github.com/stoicflame/enunciate/commit/e096e756f85690ce93c15fe6f7818b29c148a623). I guess I missed something.

Tracking at stoicflame/enunciate#259.
